version = 1

[[analyzers]]
name = "javascript"

[analyzers.meta]
environment = ["nodejs", "vitest"]

[[analyzers]]
name = "cxx"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"
