name: Test C++

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install libgtest-dev -y
          cd /usr/src/gtest
          sudo cmake -B build
          sudo cmake --build build
          sudo cp build/lib/*.a /usr/lib

      - name: Build
        run: |
          cmake -B build
          cmake --build build
        working-directory: C++

      - name: Run tests
        run: |
          cd build
          ctest
        working-directory: C++
