name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Config Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run JS tests
        run: nix develop --command bash -c "node --test"
