name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test C++
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: DeterminateSystems/determinate-nix-action@v3.8.2

      - name: Build
        run: nix develop --command bash -c "cmake -B build && cmake --build build -j$(nproc)"

      - name: Run tests
        run: nix develop --command bash -c "ctest --test-dir build"
