name: JavaScript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Config Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run tests
        run: nix develop --command bash -c "cd JS/ && node --test"
