name: Test JavaScript

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install dependencies
        run: nix develop --command bash -c "cd JavaScript && npm install"

      - name: Run JavaScript tests
        run: nix develop --command bash -c "cd JavaScript && npm test"
