name: Test C++

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: DeterminateSystems/determinate-nix-action@v3.6.2

      - name: Build
        run: nix develop --command bash -c "./x build all"

      - name: Run tests
        run: nix develop --command bash -c "./x test all"
